-- CSS Language Server
local common = require("config.lsp.common")

vim.lsp.config("cssls", {
	cmd = { vim.fn.stdpath("data") .. "/mason/bin/vscode-css-language-server", "--stdio" },
	filetypes = { "css", "scss", "less" },
	root_markers = {
		"package.json",
		".git",
		"style.css",
		"styles.css",
		"main.css",
		"index.css",
	},
	capabilities = common.capabilities,
	settings = {
		css = {
			validate = true,
			lint = {
				compatibleVendorPrefixes = "ignore",
				vendorPrefix = "warning",
				duplicateProperties = "warning",
				emptyRulesets = "warning",
				importStatement = "ignore",
				boxModel = "ignore",
				universalSelector = "ignore",
				zeroUnits = "ignore",
				fontFaceProperties = "warning",
				hexColorLength = "error",
				argumentsInColorFunction = "error",
				unknownProperties = "warning",
				ieHack = "ignore",
				unknownVendorSpecificProperties = "ignore",
				propertyIgnoredDueToDisplay = "warning",
				important = "ignore",
				float = "ignore",
				idSelector = "ignore",
			},
			completion = {
				triggerPropertyValueCompletion = true,
				completePropertyWithSemicolon = true,
			},
			hover = {
				documentation = true,
				references = true,
			},
			format = {
				enable = true,
				newlineBetweenSelectors = true,
				newlineBetweenRules = true,
				spaceAroundSelectorSeparator = true,
				braceStyle = "expand",
				maxPreserveNewLines = 2,
				preserveNewLines = true,
			},
			colorDecorators = { enable = true },
			folding = { enable = true },
		},
		scss = {
			validate = true,
			lint = {
				compatibleVendorPrefixes = "ignore",
				vendorPrefix = "warning",
				duplicateProperties = "warning",
				emptyRulesets = "warning",
				importStatement = "ignore",
				boxModel = "ignore",
				universalSelector = "ignore",
				zeroUnits = "ignore",
				fontFaceProperties = "warning",
				hexColorLength = "error",
				argumentsInColorFunction = "error",
				unknownProperties = "warning",
				ieHack = "ignore",
				unknownVendorSpecificProperties = "ignore",
				propertyIgnoredDueToDisplay = "warning",
				important = "ignore",
				float = "ignore",
				idSelector = "ignore",
			},
			completion = {
				triggerPropertyValueCompletion = true,
				completePropertyWithSemicolon = true,
			},
			hover = {
				documentation = true,
				references = true,
			},
			format = {
				enable = true,
				newlineBetweenSelectors = true,
				newlineBetweenRules = true,
				spaceAroundSelectorSeparator = true,
				braceStyle = "expand",
				maxPreserveNewLines = 2,
				preserveNewLines = true,
			},
			colorDecorators = { enable = true },
			folding = { enable = true },
		},
		less = {
			validate = true,
			lint = {
				compatibleVendorPrefixes = "ignore",
				vendorPrefix = "warning",
				duplicateProperties = "warning",
				emptyRulesets = "warning",
				importStatement = "ignore",
				boxModel = "ignore",
				universalSelector = "ignore",
				zeroUnits = "ignore",
				fontFaceProperties = "warning",
				hexColorLength = "error",
				argumentsInColorFunction = "error",
				unknownProperties = "warning",
				ieHack = "ignore",
				unknownVendorSpecificProperties = "ignore",
				propertyIgnoredDueToDisplay = "warning",
				important = "ignore",
				float = "ignore",
				idSelector = "ignore",
			},
			completion = {
				triggerPropertyValueCompletion = true,
				completePropertyWithSemicolon = true,
			},
			hover = {
				documentation = true,
				references = true,
			},
			format = {
				enable = true,
				newlineBetweenSelectors = true,
				newlineBetweenRules = true,
				spaceAroundSelectorSeparator = true,
				braceStyle = "expand",
				maxPreserveNewLines = 2,
				preserveNewLines = true,
			},
			colorDecorators = { enable = true },
			folding = { enable = true },
		},
	},
})
